# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'launcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import questions as questions
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication

from main import Questions


class Ui_Form(object):
    SCORE = 0

    def __init__(self):
        super().__init__()
        # self.mQuestionBank = list_questions
        # self.mCurrentQuestion = self.mQuestionBank.getQuestions()
        # #self.questions = None
        Questions.initialize_questions()
        self.listOfquestions = Questions.LISTESDEQUESTIONS
        self.mScore = 0
        self.mAnswer = 0
        self.q = None
        self.numberofQuestions = 0

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(903, 760)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(Qt.WA_TranslucentBackground)
        Form.setStyleSheet("font-size : 19px;\n"
                           "color:white;")
        self.label_main = QtWidgets.QLabel(Form)
        self.label_main.setGeometry(QtCore.QRect(200, 90, 441, 601))
        self.label_main.setStyleSheet("background-color:#51497A;\n"
                                      "border-radius: 40% solid black;\n"
                                      "border: 15px solid white;")
        self.label_main.setText("")
        self.label_main.setObjectName("label_main")
        self.label_score = QtWidgets.QLabel(Form)
        self.label_score.setGeometry(QtCore.QRect(270, 160, 321, 21))
        self.label_score.setText("")
        self.label_score.setObjectName("label_score")
        self.label_logo = QtWidgets.QLabel(Form)
        self.label_logo.setGeometry(QtCore.QRect(360, 30, 131, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_logo.setFont(font)
        self.label_logo.setStyleSheet("image: url(:/newPrefix/brain.png);\n"
                                      "border: solid white;\n"
                                      "border-width:0%;\n"
                                      "border-radius: 65% solid black;")
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.label_screen = QtWidgets.QLabel(Form)
        self.label_screen.setGeometry(QtCore.QRect(220, 170, 401, 141))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_screen.setFont(font)
        self.label_screen.setStyleSheet("background-color:#51497A;\n"
                                        "border: solid white;\n"
                                        "border-width:3%;\n"
                                        "border-radius: 30% solid black;\n"
                                        "")
        self.label_screen.setText("")
        self.label_screen.setWordWrap(True)
        self.label_screen.setObjectName("label_screen")
        self.btn_answer1 = QtWidgets.QPushButton(Form)
        self.btn_answer1.setGeometry(QtCore.QRect(250, 330, 341, 71))
        self.btn_answer1.setStyleSheet("background-color:#51497A;\n"
                                       "border: solid white;\n"
                                       "border-width:3%;\n"
                                       "border-radius: 30% solid black;")
        self.btn_answer1.setObjectName("btn_answer1")
        self.btn_answer2 = QtWidgets.QPushButton(Form)
        self.btn_answer2.setGeometry(QtCore.QRect(270, 420, 301, 71))
        self.btn_answer2.setStyleSheet("background-color:#51497A;\n"
                                       "border: solid white;\n"
                                       "border-width:3%;\n"
                                       "border-radius: 30% solid black;")
        self.btn_answer2.setObjectName("btn_answer2")
        self.btn_answer3 = QtWidgets.QPushButton(Form)
        self.btn_answer3.setGeometry(QtCore.QRect(280, 510, 271, 61))
        self.btn_answer3.setStyleSheet("background-color:#51497A;\n"
                                       "border: solid white;\n"
                                       "border-width:3%;\n"
                                       "border-radius: 30% solid black;")
        self.btn_answer3.setObjectName("btn_answer3")
        self.btn_retry = QtWidgets.QPushButton(Form)
        self.btn_retry.setGeometry(QtCore.QRect(500, 590, 161, 81))
        self.btn_retry.setStyleSheet("background-color:#51497A;\n"
                                     "image: url(:/rond/rond.png);\n"
                                     "border: solid white;\n"
                                     "border-width:0%;\n"
                                     "border-radius: 80% solid black;")
        self.btn_retry.setObjectName("btn_retry")
        self.btn_stop = QtWidgets.QPushButton(Form)
        self.btn_stop.setGeometry(QtCore.QRect(180, 590, 161, 81))
        self.btn_stop.setStyleSheet("background-color:#51497A;\n"
                                    "image: url(:/stop/stop.png);\n"
                                    "border: solid white;\n"
                                    "border-width:0%;\n"
                                    "border-radius: 80% solid black;")
        self.btn_stop.setText("")
        self.btn_stop.setObjectName("btn_stop")
        self.label_app_name = QtWidgets.QLabel(Form)
        self.label_app_name.setGeometry(QtCore.QRect(360, 650, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_app_name.setFont(font)
        self.label_app_name.setStyleSheet("font-size:10px")
        self.label_app_name.setObjectName("label_app_name")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # Debut du logiciel
        # self.loadQuestions()
        # self.start()
        # fin debut

        # load question

    def loadQuestions(self):
        # print(": sore = ", self.mScore)
        Questions.initialize_questions()
        self.listOfquestions = Questions.LISTESDEQUESTIONS
        self.numberofQuestions = len(self.listOfquestions)

    def reStart(self):

        self.btn_answer1.setEnabled(True)
        self.btn_answer2.setEnabled(True)
        self.btn_answer3.setEnabled(True)

        # reload json file
        Questions.initialize_questions()
        self.listOfquestions = Questions.LISTESDEQUESTIONS
        self.mScore = 0
        self.label_score.setText(f"{0}/{1}", self.mScore / self.numberofQuestions)
        self.loadQuestions()
        self.start()

    def start(self):
        self.numberofQuestions = len(self.listOfquestions)
        print("Il y ", self.numberofQuestions, " elment dans la liste")
        if not self.numberofQuestions:
            print("\n\n\n arret arret")
            # disable button
            self.btn_answer1.setEnabled(False)
            self.btn_answer2.setEnabled(False)
            self.btn_answer3.setEnabled(False)
            self.btn_answer1.setStyleSheet("background-color:gray;\n"
                                           "border: solid white;\n"
                                           "border-width:3%;\n"
                                           "border-radius: 30% solid black;")
            self.btn_answer2.setStyleSheet("background-color:gray;\n"
                                           "border: solid white;\n"
                                           "border-width:3%;\n"
                                           "border-radius: 30% solid black;")
            self.btn_answer3.setStyleSheet("background-color:gray;\n"
                                           "border: solid white;\n"
                                           "border-width:3%;\n"
                                           "border-radius: 30% solid black;")
            # self.label_score.setText(f"{0}/{1}", self.mScore/self.numberofQuestions)

        else:
            # self.mAnswer = self.listOfquestions.pop()
            self.q = self.listOfquestions.pop()
            self.printsugestion(self.q)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_answer1.setText(_translate("Form", "1 faure"))
        self.btn_answer2.setText(_translate("Form", "PushButton"))
        self.btn_answer3.setText(_translate("Form", "PushButton"))
        self.btn_retry.setText(_translate("Form", "Retry"))
        self.label_app_name.setText(_translate("Form", "One Solution Version 1.0"))

        # commane

    def stopApp(self):
        sys.exit(0)

    def r1Click(self):
        self.mAnswer = 1

    def r2Click(self):
        self.mAnswer = 2

    def r3Click(self):
        self.mAnswer = 3

    # aFFICHE LES SUGGESTIONS (TOUS SAUF LES PREMIERS ET DERNIER ELEMENTS)
    def printsugestion(self, ques):
        #     # print(q)
        #     self.q = ques
        #     a = "éèàç"
        # s.encode("utf-8").decode("utf-8")
        self.label_screen.setText(self.q.question)
        self.btn_answer1.setText(self.q.r1)
        self.btn_answer2.setText(self.q.r2)
        self.btn_answer3.setText(self.q.r3)

        self.btn_stop.clicked.connect(self.stopApp)
        self.btn_answer1.clicked.connect(self.r1Click)
        self.btn_answer2.clicked.connect(self.r2Click)
        self.btn_answer3.clicked.connect(self.r3Click)
        self.btn_answer1.clicked.connect(self.check_answer)
        self.btn_answer2.clicked.connect(self.check_answer)
        self.btn_answer3.clicked.connect(self.check_answer)

        # print("debut du jeu")

    def check_answer(self):

        if self.mAnswer == self.q.r4:
            self.mScore = self.mScore + 1
            print("reponse touvée , score =  ", self.mScore)
        else:
            print("reponse incorrect , score =  ", self.mScore)

        self.start()

    def displayQuestion(self, form, question):
        # for question in self.mQuestionBank:
        self.setupUi(form)
        self.label_screen.setText(question.question)
        self.btn_answer1.setText(question.r1)
        self.btn_answer2.setText(question.r2)
        self.btn_answer3.setText(question.r3)


import logo

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    score = 0
    ui = Ui_Form()
    ui.setupUi(Form)
    ui.start()
    Form.show()
    sys.exit(app.exec_())